spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/company
    username: admin
    password: admin
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties.javax.persistence.validation.mode: none
