spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/employee
    username: admin
    password: admin
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
  jpa:
    properties.javax.persistence.validation.mode: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: employee # id приложения


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka # адрес eureka-server для регистрации сервиса

server:
  port: 8083 # порт будет определяться eureka-server